### ISSUE TITLE
Best way to do this in 2024?

### ISSUE THREAD

**Issue by andreped** [lsaudon/pubspec_version_cli#12]
I am surprised I do not see an easy way to do this in Flutter.

Do you still actively use this tool and recommend it? Also, are there any other alternatives?

**Comment by lsaudon** [comment]
Hello @andreped,
As far as I know, there is no official way to change the version via a command line.
Yes, I use it on my current application and the previous one.
Yes, there are alternatives in Dart but I don't remember the names.
It's also possible to do it in bash.
